//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanDongHo.Domain.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class VOUCHER
    {
        public VOUCHER()
        {
            this.DONHANGs = new HashSet<DONHANG>();
        }
    
        public string MAVC { get; set; }
        public string TENVC { get; set; }
        public Nullable<double> GIATRI { get; set; }
        public Nullable<System.DateTime> NGAYTAO { get; set; }
        public Nullable<System.DateTime> NGAYHETHAN { get; set; }
    
        public virtual ICollection<DONHANG> DONHANGs { get; set; }
    }
}
